argocd: {}

apps:
  - name: data
    repoUrl: https://github.com/woog-life/data
    project: wooglife
  - name: namespaces
    repoUrl: https://github.com/torbencarstens/namespaces
    targetRevision: master
  - name: sealed-secrets
    repoUrl: https://github.com/torbencarstens/sealed-secrets
    targetRevision: master
  - name: argocd-projects
    repoUrl: https://github.com/torbencarstens/argocd-projects.git
    targetRevision: master
  - name: rbac
    repoUrl: https://github.com/torbencarstens/rbac.git
    targetRevision: master
  - name: argocd
    repoUrl: https://github.com/torbencarstens/argocd.git
    targetRevision: master
  - name: argocd-bootstrap
    repoUrl: https://github.com/openalcoholics/argocd-bootstrap.git
    targetRevision: master
  - name: ingress-controller
    repoUrl: https://github.com/torbencarstens/ingress-controller.git
    targetRevision: master
    namespace: mgmt
