argocd: {}

apps:
  - name: argocd-projects
    repoUrl: https://github.com/torbencarstens/argocd-projects.git
    targetRevision: master
    namespace: argocd
    project: argocd
    syncWave: 1
  - name: rbac
    repoUrl: https://github.com/torbencarstens/rbac.git
    targetRevision: master
    syncWave: 0
  - name: argocd
    repoUrl: https://github.com/torbencarstens/argocd.git
    targetRevision: master
    syncWave: 5
    project: argocd
    namespace: argocd
  # is this even useful?
  - name: argocd-bootstrap
    repoUrl: https://github.com/BlindfoldedSurgery/argocd-bootstrap.git
    targetRevision: main
    project: argocd
    namespace: argocd
    syncWave: 5
  - name: ingress-controller
    repoUrl: https://github.com/torbencarstens/ingress-controller.git
    targetRevision: master
    syncWave: 2
  - name: cert-manager
    repoUrl: https://github.com/torbencarstens/cert-manager.git
    targetRevision: master
    namespace: cert-manager
    syncWave: 3
  - name: longhorn
    repoUrl: https://github.com/torbencarstens/longhorn.git
    targetRevision: master
    namespace: longhorn-system
    syncWave: 6
  - name: rancher
    repoUrl: https://github.com/torbencarstens/rancher.git
    targetRevision: master
    namespace: cattle-system
    syncWave: 7
  - name: external-secrets
    repoUrl: https://github.com/torbencarstens/external-secrets.git
    targetRevision: master
    syncWave: -1
  - name: postgres-operator
    repoUrl: https://github.com/BlindfoldedSurgery/postgres-operator.git
    targetRevision: master
    namespace: postgres-operator
  - name: kubernetes-mgmt
    repoUrl: https://github.com/torbencarstens/kubernetes-mgmt.git
    targetRevision: master
  - name: song.abfahrt.io
    repoUrl: https://github.com/BlindfoldedSurgery/song.abfahrt.io
    targetRevision: master
  - name: blindfolded.surgery
    repoUrl: https://github.com/BlindfoldedSurgery/blindfolded.surgery
    targetRevision: master
  - name: datadog
    repoUrl: https://github.com/BlindfoldedSurgery/datadog
    targetRevision: main
    namespace: datadog

