{{- range .Values.apps -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
  {{- if or (not (hasKey . "deleteCascade")) (.deleteCascade) }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave | default 100 }}"
spec:
  destination:
    namespace: {{ default "argocd" .namespace }}
    server: {{ default "https://kubernetes.default.svc" .clusterUrl }}
  project: {{ default "default" .project }}
  source:
    path: {{ default "." .path }}
    repoURL: {{ .repoUrl }}
    targetRevision: {{ default "HEAD" .targetRevision }}
    {{- if or .values .valuesFile .chart }}
    helm:
      {{- if .valueFiles }}
      valueFiles:
{{ toYaml .valueFiles | indent 6 }}
      {{- end }}
      {{- if .values }}
      values: |-
{{ toYaml .values | indent 8 }}
      {{- end }}
      {{- if .chart }}
      chart: {{ .chart }}
      {{- end }}
    {{- end }}
  syncPolicy:
    automated:
      {{- if .prune }}
      # argocd has problems when default values are passed explicitly
      prune: true
      {{- end }}
      selfHeal: true
{{ end }}
