name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint
      - uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint --strict

  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: install helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade argocd-bootstrap . --install --namespace=argocd --atomic
          kubeconfig: ${{ secrets.KUBECONFIG_RAW }}
